# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
